### ISSUE TITLE
Does not work in Dragonflight (10.0)

### ISSUE THREAD

**Issue by Fiveby21** [Ketrel/IWalkAlone#1]
This addon does not seem to function at all as of the 10.0 patch.

**Comment by Ketrel** [comment]
That's unfortunately correct.  The method I was using to force the frames to show doesn't exist in DF, I'm still trying to find a way to do so that doesn't break everything and cause huge amounts of taint.

**Comment by Ketrel** [comment]
(Just to clarify, I AM trying to fix this, but I haven't found the answer yet...)

**Comment by Ketrel** [comment]
Version 2.0.0 released.  Works with Dragonflight!!!
